name: coffee_tracker
description: A new Flutter project. Created by Slidy

publish_to: 'none'


version: 1.0.0+1

## Slidy Scripts 
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  share: ^0.6.5+4
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.1+1
  http: ^0.12.2
  diacritic: ^0.1.1
  firebase_storage: ^5.2.0
  photo_view: ^0.10.3
  path: ^1.7.0
  flutter_rating_bar: ^3.2.0+1
  flutter_speed_dial: ^1.2.5
  image_picker: ^0.6.7+14
  path_provider: ^1.6.24
  validators: ^2.0.1
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter



dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: ^2.0.1
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.7
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/google-logo.png
    - images/no-image.png



