name: coffee_tracker
description: A new Flutter project. Created by Slidy

publish_to: 'none'


version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  photo_view: ^0.10.3
  select_dialog: ^1.2.3
  flutter_rating_bar: ^4.0.0
  universal_io: ^2.0.0
  share_plus: ^2.0.0
  hive_flutter: ^0.3.1
  hive: ^1.4.4+1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  diacritic: ^0.1.3
  flutter_mobx: ^1.1.0+2
  flutter_modular: ^2.0.1
  google_sign_in: ^5.0.0
  mobx: ^1.2.1+4
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_storage: ^8.0.0
  image_picker: ^0.7.2
  image_picker_for_web: ^2.0.0


dev_dependencies:
  modular_codegen: any
  mobx_codegen: any
  build_runner: any
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/google-logo.png
    - images/no-image.png
    - images/sign-up.jpg
    - images/logo.png




