name: coffee_tracker
description: A new Flutter project. Created by Slidy

publish_to: 'none'


version: 1.0.0+1

## Slidy Scripts 
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.10.0
  flutter_speed_dial: ^1.2.5
  path_provider: ^1.6.24
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  validators: ^2.0.1
  shared_preferences: ^0.5.12+2
  google_sign_in: ^4.5.5
  firebase_auth: ^0.18.1+2
  firebase: ^7.3.2
  firebase_core: ^0.5.0+1
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+3
  flutter_modular:
  flutter:
    sdk: flutter



dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.1+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/google-logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

