name: coffee_tracker
description: A new Flutter project. Created by Slidy

publish_to: 'none'


version: 1.0.0+1

## Slidy Scripts 
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  esys_flutter_share: ^1.0.2
  hive_flutter: ^0.3.1
  hive: ^1.4.4+1
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.2
  diacritic: ^0.1.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  file_picker: ^2.1.6
  firebase_storage: ^7.0.0
  flutter_mobx: ^1.1.0+2
  flutter_modular: ^2.0.1
  flutter_rating_bar: ^3.2.0+1
  flutter_speed_dial: ^2.1.1
  google_sign_in: ^4.5.9
  http: ^0.12.2
  mobx: ^1.2.1+4
  path: ^1.7.0
  photo_view: ^0.10.3
  provider: ^4.3.3
  share: ^0.6.5+4
  validators: ^2.0.1

dev_dependencies:
  mockito: ^4.1.4
  modular_codegen: ^2.1.0
  mobx_codegen: ^1.1.2
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/google-logo.png
    - images/no-image.png
    - images/sign-up.jpg
    - images/logo.png
    - images/demo-restaurant.jpg



